# Generated by Django 3.0.5 on 2020-04-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_auto_20181030_1605"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("registered", "Registered"),
                    ("closed", "Closed"),
                ],
                default="registered",
                help_text="Designates who can view your profile.",
                max_length=15,
                verbose_name="privacy",
            ),
        ),
    ]
