# Generated by Django 2.0.9 on 2019-01-04 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Short title for this profile', max_length=64)),
                ('description', models.CharField(blank=True, default='', help_text='Short description of this profile, max 1024 characters.', max_length=1024)),
                ('Basic', models.BooleanField(default=True, help_text='Basic confidentiality profile. DICOM standard anonymization')),
                ('CleanPixelData', models.BooleanField(default=True, help_text='Try to remove any burned in annotations')),
                ('CleanVisualFeatures', models.BooleanField(default=True, help_text='Try to remove or scramble face if this is present in the data ')),
                ('CleanGraphics', models.BooleanField(default=True, help_text='Remove graphics, text annotations or overlays. Does not include structured reports')),
                ('CleanStructuredContent', models.BooleanField(default=True, help_text='Clean information encoded in SR Content Items or Acquisition Context or Specimen Preparation Sequence Items ')),
                ('CleanDescriptors', models.BooleanField(default=True, help_text='Clean free text fields like study description')),
                ('RetainFullDates', models.BooleanField(default=True, help_text='Keep date and time information')),
                ('RetainModifiedDates', models.BooleanField(default=True, help_text='Add a certain increment to date and time information')),
                ('RetainPatientCharacteristics', models.BooleanField(default=True, help_text='Keep information like age, sex, height and weight')),
                ('RetainDeviceIdentity', models.BooleanField(default=True, help_text='Keep information about the device the scan was made on')),
                ('RetainUIDs', models.BooleanField(default=True, help_text='Keep IDs such as study UID, patient ID etc.')),
                ('RetainSafePrivate', models.BooleanField(default=True, help_text='Keep private tags that are explicitly marked as not containing any patient information')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Profile'),
        ),
    ]
